databases:
  - name: points
    databaseName: points
    user: points

services:
  - type: web
    name: points
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: points
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
